apiVersion: apis.intility.no/v1alpha1
kind: FastAPIInstance
metadata:
  namespace: my-claims
  name: my-fastapi
spec:
  parameters:
    image: web-api
    namespace: myapp
    repoUrl: "https://github.com/daniwk/crossplane-k8s-xrd-.git"